"""Añadido el campo last_login al modelo User

Revision ID: 75c36fb08eb9
Revises: af0c0451cfec
Create Date: 2024-09-05 06:27:05.106771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c36fb08eb9'
down_revision = 'af0c0451cfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
