"""Increase length of password_hash field

Revision ID: 82172db423b8
Revises: 75c36fb08eb9
Create Date: 2024-09-10 18:36:27.918374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82172db423b8'
down_revision = '75c36fb08eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
